name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^3.2.0
  google_fonts: ^8.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  speech_to_text: ^7.3.0
  supabase_flutter: ^2.12.0
  camera: ^0.11.0+1
  web_socket_channel: ^3.0.3
  path_provider: ^2.1.5
  record: ^6.1.0
  shadcn_ui: ^0.45.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/
